version: "3.3"

# Building:
#
# $ docker-compose up --no-start --build
#

services:
    #--------------------------------------------------------------------------#
    # Geant4 container
    geant4:
      image: geantx/geant4
      stdin_open: true
      tty: true
      build:
        context: .
        dockerfile: Dockerfile
        args:
          BASE_IMG: "ubuntu"
          BASE_TAG: "latest"
          COMPILER_TYPE: "gcc"
          COMPILER_VERSION: "7"
          BUILD_TYPE: "Release"
          TIMEMORY: "ON"
          SOFTWARE: "geant4"

    #--------------------------------------------------------------------------#
    # GeantV container
    geantv:
      image: geantx/geantv
      stdin_open: true
      tty: true
      build:
        context: .
        dockerfile: Dockerfile
        args:
          BASE_IMG: "ubuntu"
          BASE_TAG: "latest"
          COMPILER_TYPE: "gcc"
          COMPILER_VERSION: "7"
          BUILD_TYPE: "Release"
          TIMEMORY: "ON"
          SOFTWARE: "geantv"

    #--------------------------------------------------------------------------#
    # GeantX development container
    geantx-dev:
      image: geantx/geantx-dev
      stdin_open: true
      tty: true
      build:
        context: .
        dockerfile: Dockerfile
        args:
          BASE_IMG: "nvidia/cuda"
          BASE_TAG: "10.0-devel-ubuntu18.04"
          COMPILER_TYPE: "gcc"
          COMPILER_VERSION: "7"
          BUILD_TYPE: "Release"
          TIMEMORY: "ON"
          SOFTWARE: "geantx-dev"

    #--------------------------------------------------------------------------#
    # GeantX development container
    geantx-dev-edge:
      image: geantx/geantx-dev:cuda10.1
      stdin_open: true
      tty: true
      build:
        context: .
        dockerfile: Dockerfile
        args:
          BASE_IMG: "nvidia/cuda"
          BASE_TAG: "10.1-devel-ubuntu18.04"
          COMPILER_TYPE: "gcc"
          COMPILER_VERSION: "7"
          BUILD_TYPE: "Release"
          TIMEMORY: "ON"
          SOFTWARE: "geantx-dev"
          REQUIRE_CUDA_VERSION: "10.1"

    #--------------------------------------------------------------------------#
    # Geant4 + GeantV container
    geant4v:
      image: geantx/geant4v
      stdin_open: true
      tty: true
      build:
        context: .
        dockerfile: Dockerfile
        args:
          BASE_IMG: "geantx/geant4"
          BASE_TAG: "latest"
          COMPILER_TYPE: "gcc"
          COMPILER_VERSION: "7"
          BUILD_TYPE: "Release"
          TIMEMORY: "ON"
          SOFTWARE: "geant4v"
